services:
  frontend:
    image: node:21-alpine3.18
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000

  backend:
    image: node:21-alpine3.18
    volumes:
      - ./api:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - 4000:4000
